Feature/contact page
pushkurella/kdc-website pull request #3
Opened 2020-04-01 20:01 UTC by pushkurella

2020-04-01 20:18 UTC, richard-fu1 requested changes
I think you need to npm i --save google-map-react

2020-04-01 20:32 UTC, ditto000 commented
Also, the map seems to be really slow to interact with, maybe just me though

2020-04-02 13:57 UTC, ali-sadri approved these changes

2020-04-02 14:12 UTC, pushkurella commented
> I think you need to npm i --save google-map-react

this is fixed, i was thinking the new npm update would automatically save it to package.json , not sure only sometimes this happens

2020-04-02 14:32 UTC, richard-fu1 approved these changes

2020-04-02 14:38 UTC, merged